// <auto-generated />
using System;
using KineStat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KineStat.Migrations
{
    [DbContext(typeof(KineDbContext))]
    [Migration("20251128161644_madeHeightAndWeightNullable")]
    partial class madeHeightAndWeightNullable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("KineStat.Models.Administrator", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Administrators");
                });

            modelBuilder.Entity("KineStat.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int?>("QuestionQCMId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.HasIndex("QuestionQCMId");

                    b.ToTable("Answers");
                });

            modelBuilder.Entity("KineStat.Models.Assessment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("DossierId")
                        .HasColumnType("integer");

                    b.Property<int?>("MedicalRecordId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("PhysioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("DossierId");

                    b.HasIndex("MedicalRecordId");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysioId");

                    b.ToTable("Assessments");
                });

            modelBuilder.Entity("KineStat.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Prior")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Categories");
                });

            modelBuilder.Entity("KineStat.Models.ClinicalData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PatientId");

                    b.ToTable("ClinicalDatas");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cluster");
                });

            modelBuilder.Entity("KineStat.Models.Dossier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Notes")
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Dossiers");
                });

            modelBuilder.Entity("KineStat.Models.MedicalContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("MedicalContexts");
                });

            modelBuilder.Entity("KineStat.Models.MedicalRecord", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArchivedAt")
                        .HasColumnType("date");

                    b.Property<bool>("IsArchived")
                        .HasColumnType("boolean");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("MedicalRecords");
                });

            modelBuilder.Entity("KineStat.Models.Pathology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Prior")
                        .HasColumnType("double precision");

                    b.Property<int?>("RedFlagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RedFlagId");

                    b.ToTable("Pathologies");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .HasColumnType("text");

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("DoctorINAMI")
                        .HasColumnType("text");

                    b.Property<string>("DoctorName")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Gender")
                        .HasColumnType("integer");

                    b.Property<double?>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientStatus")
                        .HasColumnType("integer");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhysioId")
                        .HasColumnType("integer");

                    b.Property<string>("SocialSecurityNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PhysioId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("KineStat.Models.PatientAnswer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Comment")
                        .HasColumnType("text");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("PatientId");

                    b.HasIndex("QuestionId");

                    b.ToTable("PatientAnswers");

                    b.HasDiscriminator().HasValue("PatientAnswer");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KineStat.Models.Physio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("INAMINumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Physios");
                });

            modelBuilder.Entity("KineStat.Models.PriorContext", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("MedicalContextId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("MedicalContextId");

                    b.ToTable("PriorContexts");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<double>("RVNegative")
                        .HasColumnType("double precision");

                    b.Property<double>("RVPositive")
                        .HasColumnType("double precision");

                    b.Property<string>("SourceRv")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("ClusterId");

                    b.ToTable("Questions");

                    b.HasDiscriminator().HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KineStat.Models.Redflag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<int>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("AssessmentId");

                    b.HasIndex("CategoryId");

                    b.HasIndex("PatientId");

                    b.ToTable("Redflags");
                });

            modelBuilder.Entity("KineStat.Models.RedflagThreshold", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("ThresholdPercentage")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("RedflagThresholds");
                });

            modelBuilder.Entity("KineStat.Models.Socrate", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("AssessmentId")
                        .HasColumnType("integer");

                    b.Property<string>("Association")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Character")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ExacerbatingFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Onset")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<string>("Radiation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("RelievingFactor")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Site")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Timing")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("Socrates");
                });

            modelBuilder.Entity("PathologyQuestion", b =>
                {
                    b.Property<int>("PathologiesId")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionsId")
                        .HasColumnType("integer");

                    b.HasKey("PathologiesId", "QuestionsId");

                    b.HasIndex("QuestionsId");

                    b.ToTable("PathologyQuestion");
                });

            modelBuilder.Entity("KineStat.Models.PatientAnswerBool", b =>
                {
                    b.HasBaseType("KineStat.Models.PatientAnswer");

                    b.Property<bool>("Value")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("PatientAnswerBool");
                });

            modelBuilder.Entity("KineStat.Models.PatientAnswerNumeric", b =>
                {
                    b.HasBaseType("KineStat.Models.PatientAnswer");

                    b.Property<double>("Value")
                        .HasColumnType("double precision");

                    b.ToTable("PatientAnswers", t =>
                        {
                            t.Property("Value")
                                .HasColumnName("PatientAnswerNumeric_Value");
                        });

                    b.HasDiscriminator().HasValue("PatientAnswerNumeric");
                });

            modelBuilder.Entity("KineStat.Models.PatientAnswerQCM", b =>
                {
                    b.HasBaseType("KineStat.Models.PatientAnswer");

                    b.Property<int>("AnswerId")
                        .HasColumnType("integer");

                    b.HasIndex("AnswerId");

                    b.HasDiscriminator().HasValue("PatientAnswerQCM");
                });

            modelBuilder.Entity("KineStat.Models.QuestionBool", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.HasDiscriminator().HasValue("QuestionBool");
                });

            modelBuilder.Entity("KineStat.Models.QuestionLadder", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.Property<int>("Max")
                        .HasColumnType("integer");

                    b.Property<int>("Min")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("QuestionLadder");
                });

            modelBuilder.Entity("KineStat.Models.QuestionQCM", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.HasDiscriminator().HasValue("QuestionQCM");
                });

            modelBuilder.Entity("KineStat.Models.Answer", b =>
                {
                    b.HasOne("KineStat.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.QuestionQCM", null)
                        .WithMany("Choices")
                        .HasForeignKey("QuestionQCMId");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KineStat.Models.Assessment", b =>
                {
                    b.HasOne("KineStat.Models.Dossier", "Dossier")
                        .WithMany("Assessments")
                        .HasForeignKey("DossierId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.MedicalRecord", null)
                        .WithMany("Assessments")
                        .HasForeignKey("MedicalRecordId");

                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany("Assessments")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Physio", "Physio")
                        .WithMany()
                        .HasForeignKey("PhysioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dossier");

                    b.Navigation("Patient");

                    b.Navigation("Physio");
                });

            modelBuilder.Entity("KineStat.Models.ClinicalData", b =>
                {
                    b.HasOne("KineStat.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.HasOne("KineStat.Models.Category", null)
                        .WithMany("Clusters")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("KineStat.Models.Dossier", b =>
                {
                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany("Dossiers")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KineStat.Models.Pathology", b =>
                {
                    b.HasOne("KineStat.Models.Category", null)
                        .WithMany("Pathologies")
                        .HasForeignKey("CategoryId");

                    b.HasOne("KineStat.Models.Redflag", "RedFlag")
                        .WithMany()
                        .HasForeignKey("RedFlagId");

                    b.Navigation("RedFlag");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.HasOne("KineStat.Models.Physio", "Physio")
                        .WithMany("Patients")
                        .HasForeignKey("PhysioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physio");
                });

            modelBuilder.Entity("KineStat.Models.PatientAnswer", b =>
                {
                    b.HasOne("KineStat.Models.Assessment", "Assessment")
                        .WithMany()
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Assessment");

                    b.Navigation("Patient");

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KineStat.Models.PriorContext", b =>
                {
                    b.HasOne("KineStat.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.MedicalContext", "MedicalContext")
                        .WithMany("PriorContexts")
                        .HasForeignKey("MedicalContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("MedicalContext");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.HasOne("KineStat.Models.Assessment", null)
                        .WithMany("Questions")
                        .HasForeignKey("AssessmentId");

                    b.HasOne("KineStat.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Cluster", "Cluster")
                        .WithMany("Questions")
                        .HasForeignKey("ClusterId");

                    b.Navigation("Category");

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("KineStat.Models.Redflag", b =>
                {
                    b.HasOne("KineStat.Models.Assessment", null)
                        .WithMany("RedFlagsDetected")
                        .HasForeignKey("AssessmentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("KineStat.Models.Socrate", b =>
                {
                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");
                });

            modelBuilder.Entity("PathologyQuestion", b =>
                {
                    b.HasOne("KineStat.Models.Pathology", null)
                        .WithMany()
                        .HasForeignKey("PathologiesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Question", null)
                        .WithMany()
                        .HasForeignKey("QuestionsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KineStat.Models.PatientAnswerQCM", b =>
                {
                    b.HasOne("KineStat.Models.Answer", "ChosenAnswer")
                        .WithMany()
                        .HasForeignKey("AnswerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChosenAnswer");
                });

            modelBuilder.Entity("KineStat.Models.Assessment", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("RedFlagsDetected");
                });

            modelBuilder.Entity("KineStat.Models.Category", b =>
                {
                    b.Navigation("Clusters");

                    b.Navigation("Pathologies");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KineStat.Models.Dossier", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("KineStat.Models.MedicalContext", b =>
                {
                    b.Navigation("PriorContexts");
                });

            modelBuilder.Entity("KineStat.Models.MedicalRecord", b =>
                {
                    b.Navigation("Assessments");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.Navigation("Assessments");

                    b.Navigation("Dossiers");
                });

            modelBuilder.Entity("KineStat.Models.Physio", b =>
                {
                    b.Navigation("Patients");
                });

            modelBuilder.Entity("KineStat.Models.QuestionQCM", b =>
                {
                    b.Navigation("Choices");
                });
#pragma warning restore 612, 618
        }
    }
}
