// <auto-generated />
using System;
using System.Collections.Generic;
using KineStat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace KineStat.Migrations
{
    [DbContext(typeof(KineDbContext))]
    [Migration("20251113184641_addedTypeDateAnnotation")]
    partial class addedTypeDateAnnotation
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BilanRedflag", b =>
                {
                    b.Property<int>("BilansId")
                        .HasColumnType("integer");

                    b.Property<int>("RedFlagsDetectedId")
                        .HasColumnType("integer");

                    b.HasKey("BilansId", "RedFlagsDetectedId");

                    b.HasIndex("RedFlagsDetectedId");

                    b.ToTable("BilanRedflag");
                });

            modelBuilder.Entity("KineStat.Models.AnswerBool", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("BoolValue")
                        .HasColumnType("boolean");

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerBool");
                });

            modelBuilder.Entity("KineStat.Models.AnswerLadder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("LadderValue")
                        .HasColumnType("integer");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerLadder");
                });

            modelBuilder.Entity("KineStat.Models.AnswerQCM", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("QuestionId")
                        .HasColumnType("integer");

                    b.Property<int>("Score")
                        .HasColumnType("integer");

                    b.PrimitiveCollection<List<string>>("SelectedAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("AnswerQCM");
                });

            modelBuilder.Entity("KineStat.Models.Bilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<int>("PatientId")
                        .HasColumnType("integer");

                    b.Property<int>("PhysioId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.HasIndex("PhysioId");

                    b.ToTable("Bilan");
                });

            modelBuilder.Entity("KineStat.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Prior")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Category");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Cluster");
                });

            modelBuilder.Entity("KineStat.Models.Pathology", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CategorieId")
                        .HasColumnType("integer");

                    b.Property<int?>("CategoryId")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Prior")
                        .HasColumnType("double precision");

                    b.Property<int?>("RedFlagId")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("RedFlagId");

                    b.ToTable("Pathology");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Genre")
                        .HasColumnType("integer");

                    b.Property<double>("Height")
                        .HasColumnType("double precision");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("PhysioId")
                        .HasColumnType("integer");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.HasIndex("PhysioId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("KineStat.Models.Physio", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("INAMINumber")
                        .HasColumnType("integer");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Physio");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("BilanID")
                        .HasColumnType("integer");

                    b.Property<int?>("ClusterId")
                        .HasColumnType("integer");

                    b.Property<string>("Discriminator")
                        .IsRequired()
                        .HasMaxLength(21)
                        .HasColumnType("character varying(21)");

                    b.Property<double>("RVNegatif")
                        .HasColumnType("double precision");

                    b.Property<double>("RVPositif")
                        .HasColumnType("double precision");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("BilanID");

                    b.HasIndex("ClusterId");

                    b.ToTable("Question");

                    b.HasDiscriminator().HasValue("Question");

                    b.UseTphMappingStrategy();
                });

            modelBuilder.Entity("KineStat.Models.Redflag", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int>("Category")
                        .HasColumnType("integer");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("SeverityLevel")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("Redflags");
                });

            modelBuilder.Entity("KineStat.Models.QuestionBool", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.Property<bool>("Answer")
                        .HasColumnType("boolean");

                    b.HasDiscriminator().HasValue("QuestionBool");
                });

            modelBuilder.Entity("KineStat.Models.QuestionLadder", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.Property<int>("max")
                        .HasColumnType("integer");

                    b.Property<int>("min")
                        .HasColumnType("integer");

                    b.HasDiscriminator().HasValue("QuestionLadder");
                });

            modelBuilder.Entity("KineStat.Models.QuestionQCM", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.PrimitiveCollection<List<string>>("ListAnswers")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.HasDiscriminator().HasValue("QuestionQCM");
                });

            modelBuilder.Entity("BilanRedflag", b =>
                {
                    b.HasOne("KineStat.Models.Bilan", null)
                        .WithMany()
                        .HasForeignKey("BilansId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Redflag", null)
                        .WithMany()
                        .HasForeignKey("RedFlagsDetectedId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KineStat.Models.AnswerBool", b =>
                {
                    b.HasOne("KineStat.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KineStat.Models.AnswerLadder", b =>
                {
                    b.HasOne("KineStat.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KineStat.Models.AnswerQCM", b =>
                {
                    b.HasOne("KineStat.Models.Question", "Question")
                        .WithMany()
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KineStat.Models.Bilan", b =>
                {
                    b.HasOne("KineStat.Models.Patient", "Patient")
                        .WithMany("Bilans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Physio", "Physio")
                        .WithMany("Bilans")
                        .HasForeignKey("PhysioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Patient");

                    b.Navigation("Physio");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.HasOne("KineStat.Models.Category", null)
                        .WithMany("Clusters")
                        .HasForeignKey("CategoryId");
                });

            modelBuilder.Entity("KineStat.Models.Pathology", b =>
                {
                    b.HasOne("KineStat.Models.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryId");

                    b.HasOne("KineStat.Models.Redflag", "RedFlag")
                        .WithMany("Pathologies")
                        .HasForeignKey("RedFlagId");

                    b.Navigation("Category");

                    b.Navigation("RedFlag");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.HasOne("KineStat.Models.Physio", "Physio")
                        .WithMany("Patients")
                        .HasForeignKey("PhysioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Physio");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.HasOne("KineStat.Models.Bilan", null)
                        .WithMany("Questions")
                        .HasForeignKey("BilanID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Cluster", "Cluster")
                        .WithMany("Questions")
                        .HasForeignKey("ClusterId");

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("KineStat.Models.Bilan", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KineStat.Models.Category", b =>
                {
                    b.Navigation("Clusters");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.Navigation("Bilans");
                });

            modelBuilder.Entity("KineStat.Models.Physio", b =>
                {
                    b.Navigation("Bilans");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("KineStat.Models.Redflag", b =>
                {
                    b.Navigation("Pathologies");
                });
#pragma warning restore 612, 618
        }
    }
}
