// <auto-generated />
using System;
using KineStat.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace KineStat.Migrations
{
    [DbContext(typeof(KineDbContext))]
    [Migration("20251108162728_updateKineClass")]
    partial class updateKineClass
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("KineStat.Models.Answer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("QuestionId")
                        .HasColumnType("int");

                    b.Property<int>("Score")
                        .HasColumnType("int");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId")
                        .IsUnique();

                    b.ToTable("Answer");
                });

            modelBuilder.Entity("KineStat.Models.Bilan", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int>("KineId")
                        .HasColumnType("int");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("KineId");

                    b.HasIndex("PatientId");

                    b.ToTable("Bilan");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Cluster");
                });

            modelBuilder.Entity("KineStat.Models.Kine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("INAMINumber")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Kine");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("BirthDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Genre")
                        .HasColumnType("int");

                    b.Property<double>("Height")
                        .HasColumnType("float");

                    b.Property<int?>("KineId")
                        .HasColumnType("int");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<double>("Weight")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("KineId");

                    b.ToTable("Patients");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ClusterId")
                        .HasColumnType("int");

                    b.Property<double>("RVNegatif")
                        .HasColumnType("float");

                    b.Property<double>("RVPositif")
                        .HasColumnType("float");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ClusterId");

                    b.ToTable("Question");

                    b.UseTptMappingStrategy();
                });

            modelBuilder.Entity("KineStat.Models.RedFlags", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("BilanId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("BilanId");

                    b.ToTable("Redflags");
                });

            modelBuilder.Entity("KineStat.Models.QuestionBool", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.ToTable("QuestionBool");
                });

            modelBuilder.Entity("KineStat.Models.QuestionLadder", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.Property<int>("max")
                        .HasColumnType("int");

                    b.Property<int>("min")
                        .HasColumnType("int");

                    b.ToTable("QuestionLadder");
                });

            modelBuilder.Entity("KineStat.Models.QuestionQCM", b =>
                {
                    b.HasBaseType("KineStat.Models.Question");

                    b.PrimitiveCollection<string>("ListAnswers")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.ToTable("QuestionQCM");
                });

            modelBuilder.Entity("KineStat.Models.Answer", b =>
                {
                    b.HasOne("KineStat.Models.Question", "Question")
                        .WithOne("answer")
                        .HasForeignKey("KineStat.Models.Answer", "QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("KineStat.Models.Bilan", b =>
                {
                    b.HasOne("KineStat.Models.Kine", null)
                        .WithMany("Bilans")
                        .HasForeignKey("KineId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("KineStat.Models.Patient", null)
                        .WithMany("Bilans")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.HasOne("KineStat.Models.Kine", null)
                        .WithMany("Patients")
                        .HasForeignKey("KineId");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.HasOne("KineStat.Models.Cluster", "Cluster")
                        .WithMany("Questions")
                        .HasForeignKey("ClusterId");

                    b.Navigation("Cluster");
                });

            modelBuilder.Entity("KineStat.Models.RedFlags", b =>
                {
                    b.HasOne("KineStat.Models.Bilan", null)
                        .WithMany("RedFlagsDetected")
                        .HasForeignKey("BilanId");
                });

            modelBuilder.Entity("KineStat.Models.QuestionBool", b =>
                {
                    b.HasOne("KineStat.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("KineStat.Models.QuestionBool", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KineStat.Models.QuestionLadder", b =>
                {
                    b.HasOne("KineStat.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("KineStat.Models.QuestionLadder", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KineStat.Models.QuestionQCM", b =>
                {
                    b.HasOne("KineStat.Models.Question", null)
                        .WithOne()
                        .HasForeignKey("KineStat.Models.QuestionQCM", "Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("KineStat.Models.Bilan", b =>
                {
                    b.Navigation("RedFlagsDetected");
                });

            modelBuilder.Entity("KineStat.Models.Cluster", b =>
                {
                    b.Navigation("Questions");
                });

            modelBuilder.Entity("KineStat.Models.Kine", b =>
                {
                    b.Navigation("Bilans");

                    b.Navigation("Patients");
                });

            modelBuilder.Entity("KineStat.Models.Patient", b =>
                {
                    b.Navigation("Bilans");
                });

            modelBuilder.Entity("KineStat.Models.Question", b =>
                {
                    b.Navigation("answer")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
